### ISSUE TITLE
Importing test library 'SeleniumLibrary' failed: ImportError: No module named selenium

### ISSUE THREAD

**Issue by imoital** [robotframework/MavenPlugin#57]
I'm trying to import the 'SeleniumLibrary' as explained were: http://robotframework.org/MavenPlugin/examples/seleniumlibrary.html

But I'm getting this error:
`[ ERROR ] Error in file '/Users/inesmoital/Projects/INMS/web-app/test/robotframework/acceptance/open_parameters.robot': Importing test library 'SeleniumLibrary' failed: ImportError: No module named selenium
Traceback (most recent call last):
  File "/Users/inesmoital/Projects/INMS/web-app/resources/robotframework/libraries/SeleniumLibrary/__init__.py", line 22, in <module>
    from SeleniumLibrary.base import DynamicCore
  File "/Users/inesmoital/Projects/INMS/web-app/resources/robotframework/libraries/SeleniumLibrary/base/__init__.py", line 17, in <module>
    from .context import ContextAware
  File "/Users/inesmoital/Projects/INMS/web-app/resources/robotframework/libraries/SeleniumLibrary/base/context.py", line 17, in <module>
    from SeleniumLibrary.utils import escape_xpath_value
  File "/Users/inesmoital/Projects/INMS/web-app/resources/robotframework/libraries/SeleniumLibrary/utils/__init__.py", line 21, in <module>
    from .seleniumversion import SELENIUM_VERSION
  File "/Users/inesmoital/Projects/INMS/web-app/resources/robotframework/libraries/SeleniumLibrary/utils/seleniumversion.py", line 19, in <module>
    import selenium
PYTHONPATH:
  /Users/inesmoital/Projects/INMS/web-app/resources/robotframework/libraries
  /Users/inesmoital/.m2/repository/org/robotframework/robotframework/3.1/Lib
  /Users/inesmoital/.m2/repository/org/robotframework/robotframework/3.1/robotframework-3.1.jar/Lib
  __classpath__
  __pyclasspath__/
CLASSPATH:
  /usr/local/Cellar/maven/3.6.0/libexec/boot/plexus-classworlds-2.5.2.jar`

I tried to install the library with 'pip' but I'm getting the same error.

Am I doing something wrong?

**Comment by Hi-Fi** [comment]
It might be that before all the dependencies were also included with the library sources. The issue comes because there's no selenium available which is the dependency of the library.

Requirements are listed at https://github.com/robotframework/SeleniumLibrary/blob/master/requirements.txt.
